spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML   ,HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #prefix: classpath:

server:
  port: 8080 #更改tomcat端口